CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    BLOCKED BOOLEAN NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS USER_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS EMPLOYEES (
    ID BIGINT PRIMARY KEY,
    PHONE VARCHAR(50) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    CONSTRAINT FK_EMPLOYEE_USER
        FOREIGN KEY (ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS CLIENTS (
    ID BIGINT PRIMARY KEY,
    BALANCE DECIMAL(19,2) NOT NULL,
    CONSTRAINT FK_CLIENT_USER
        FOREIGN KEY (ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS BOOKS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    GENRE VARCHAR(255),
    AGE_GROUP VARCHAR(20) NOT NULL,
    PRICE DECIMAL(19,2),
    PUBLICATION_DATE DATE,
    AUTHOR VARCHAR(255),
    NUMBER_OF_PAGES INT,
    CHARACTERISTICS VARCHAR(1000),
    DESCRIPTION VARCHAR(2000),
    LANGUAGE VARCHAR(20) NOT NULL,
    ACTIVE BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID BIGINT NOT NULL,
    EMPLOYEE_ID BIGINT,
    ORDER_DATE TIMESTAMP,
    PRICE DECIMAL(19,2),
    ORDER_STATUS VARCHAR(20) NOT NULL,
    CONSTRAINT FK_ORDER_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID),
    CONSTRAINT FK_ORDER_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID)
);

CREATE TABLE IF NOT EXISTS BOOKITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    BOOK_ID BIGINT NOT NULL,
    QUANTITY INT,
    CONSTRAINT FK_BOOKITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    CONSTRAINT FK_BOOKITEM_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID)
);
